# SPDX-FileCopyrightText: 1997 Argonne National Laboratory
#
# SPDX-License-Identifier: EPICS

TOP = ..
include $(TOP)/configure/CONFIG
DIRS += $(wildcard src* *Src*)
DIRS += $(wildcard db* *Db*)
include $(TOP)/configure/RULES_DIRS
